### ISSUE TITLE
question about output format

### ISSUE THREAD

**Issue by liuzhaoyanglzy** [raphael-group/STARCH#8]
Hello.

I have a question about the output file "label_xxxx.csv". Is the number 0 representative of Normal and number 1 to number of argument "n_clusters" representative of clones?

Since I input n_clusters = 3 and didn't input normal_spots. And the result "label_xxxx.csv" ranges from 0 to 3.

Thank you!

**Comment by RonZeira** [comment]
The last cluster (3 in your case) should be the normal spots.
